### ISSUE TITLE
Using getting results from state using extractMentions method

### ISSUE THREAD

**Issue by BeckySharp** [lum-ai/odinson#143]
While we can write patterns against things in the state using the `query` methods directly (e.g., https://github.com/lum-ai/odinson/blob/907a6e111badf57dbb7bd5c415f0f4c28889a89d/core/src/test/scala/ai/lum/odinson/events/TestEvents.scala#L154),

when we tried to do the same from the "outside" using the `extractMentions` method, it did not work (seems like things aren't making it into the state, or else the state is not being persisted enough to get them.

We used this rule file:
```
rules:
  # Find a component for the next rule
  - name: person-ner
    type: basic
    label: Person
    priority: 1
    pattern: |
      [entity=/PERSON/]

  - name: action-test
    type: event
    label: X
    priority: 2
    pattern:
      trigger = [tag=/V.*/]
      agent:Person = >nsubj
```

and this API call:
```
  // get the extractor engine
  val ee = ExtractorEngine.fromConfig
  val rr = ee.ruleReader
  // load rule file from resources
  val rulesResource = getClass.getResourceAsStream("/grammars/umbc.yml")
  val rules = Source.fromInputStream(rulesResource).getLines.mkString("\n")
  // compile query
  val queries = rr.compileRuleFile(rules)
  // extract mentions
  val mentions = ee.extractMentions(queries)
  for (m <- mentions) {
    if (m.label.get != "Person") {
      println(m)
    }
  }
```

If we don't type restrict the agent arg, we get stuff, but when we do (i.e., when we make the agent be a previously found Person), we don't.  Using the first rule on its own we get stuff too, so it is finding them.

ping @gcgbarbosa
