### ISSUE TITLE
Unable to filter using metadata

### ISSUE THREAD

**Issue by victoryhb** [lum-ai/odinson#328]
I am experimenting with a custom annotation pipeline to generate Odinson documents for indexing. After some trial and error (since I couldn't find related info in the docs:), I was able to index the documents along with some metadata. The current metadata of one of my files as shown via Odinson's REST API interface (/api/metadata/by-document-id, version 0.5.1 Snapshot) is something like the following:
```
[
  {
    "$type": "ai.lum.odinson.StringField",
    "name": "file",
    "string": "AAT"
  },
  {
    "$type": "ai.lum.odinson.StringField",
    "name": "corpus",
    "string": "BNC"
  }
]
```

However, when trying to filter documents with the filter: corpus=='BNC',  either using the parentQuery of /api/execute/pattern or defining the metadataFilters parameter through /api/execute/grammar,  no results were returned (the results were correctly returned without the filter). Below is the grammar I tested with:

```
metadataFilters: 
 - corpus=='BNC'

rules:
 - name: "example"
   label: GrammaticalSubject
   type: event
   pattern: |
     trigger = [lemma=have]
     subject  = >nsubj []
```

I wonder if I am doing anything wrong here?
